### ISSUE TITLE
Albany LCM CDash issues

### ISSUE THREAD

**Issue by ikalash** [sandialabs/LCM#50]
Due to a change in the SEMS-supported CDash sites, CEE can no longer post to the site due to firewall issues. So one will not see the cee nightly build on the CDash site for now. 

A consequence of the change is that the post-processing script for querying the SON CDash site and sending an email is broken too. There is a SEMS ticket out on this, which @bartlettroscoe is working on.

**Comment by bartlettroscoe** [comment]
@ikalash, wait, you can't even submit data to the CDash site after the upgrade?  So that is not a problem with Python code in cdash_analyze_and_report.py.  That is a problem with the CDash site itself.  The SEMS O&M team will need to address this.

**Comment by ikalash** [comment]
https://github.com/sandialabs/Albany/issues/758
