### ISSUE TITLE
Fix calls to deprecated Tpetra functions

### ISSUE THREAD

**Issue by ikalash** [sandialabs/LCM#53]
Tpetra is deprecating some functionality used in Albany and hence LCM - please see the following issue in Albany for details: https://github.com/sandialabs/Albany/issues/763 .  The deprecated code will be removed at the beginning of February.  We need to get the code to work w/o the deprecated code by then.

**Comment by ikalash** [comment]
More specifically, it seems the deprecation will happen 2/8.  The following is from an email sent by Jim Willenbring:


All,

Bottom line up front:

February 8th – target date for next Trilinos minor release – version 13.4. After this date, deprecated code may be removed from the code base at any time. Code may be deprecated any time prior to this date.

May 17th – target date for next Trilinos major release – version 14.0. Code deprecated prior to February 8th may be removed any time prior to this release.

Important details:

Following Trilinos' code deprecation and backward compatibility policies, the Trilinos team has begun marking code for deprecation.  Markings can be added until the next minor release of Trilinos, version 13.4 (tentatively scheduled for February 8, 2022).  Deprecated code can be removed from Trilinos after the minor release, with all deprecated code removed before the next major release, version 14.0, tentatively scheduled for May 17th, 2022.

After the minor release, users will want to remove all calls to deprecated code from their code base prior to updating from the develop or master branches.

To test your package or application without the most significant deprecations in preparation for these changes, build Trilinos with
   -D Tpetra_ENABLE_DEPRECATED_CODE=OFF \
   -D KOKKOS_ENABLE_DEPRECATED_CODE=OFF \
   -D Ifpack2_ENABLE_DEPRECATED_CODE=OFF \
   -D MueLu_ENABLE_DEPRECATED_CODE=OFF \
   -D Xpetra_ENABLE_DEPRECATED_CODE=OFF \
   -D Belos_HIDE_DEPRECATED_CODE=ON \
   -D Epetra_HIDE_DEPRECATED_CODE=ON \
   -D Ifpack2_HIDE_DEPRECATED_CODE=ON \
   -D Panzer_HIDE_DEPRECATED_CODE=ON \
   -D Phalanx_HIDE_DEPRECATED_CODE=ON \
   -D RTop_HIDE_DEPRECATED_CODE=ON \
   -D STK_HIDE_DEPRECATED_CODE=ON \
   -D Teuchos_HIDE_DEPRECATED_CODE=ON \
   -D Thyra_HIDE_DEPRECATED_CODE=ON \
   -D Claps_HIDE_DEPRECATED_CODE=ON \
   -D GlobiPack_HIDE_DEPRECATED_CODE=ON \
   -D OptiPack_HIDE_DEPRECATED_CODE=ON \
   -D Tempus_HIDE_DEPRECATED_CODE=ON \
   -D SEACASProj_HIDE_DEPRECATED_CODE=ON \
   -D Trios_HIDE_DEPRECATED_CODE=ON \
  

A note concerning Tpetra deprecations: Most deprecation in Tpetra supports removal of the UVM requirement in Trilinos.  The effects of the deprecation will be seen most strongly on GPU platforms, and we recommend that applications and package developers test on GPU platforms (with and without UVM, if possible) when refactoring calls to deprecated code.  Details about UVM removal in Tpetra are at https://github.com/trilinos/Trilinos/wiki/Tpetra-Information-Page.

Jim Willenbring

On behalf of the Trilinos Leadership Team

**Comment by ikalash** [comment]
@mperego , @bartgol : can you please confirm that the only changes that had to be made in Albany to reflect the upcoming removal of deprecations in Trilinos are 
```
-D Tpetra_ENABLE_DEPRECATED_CODE=OFF \
-D Xpetra_ENABLE_DEPRECATED_CODE=OFF \
```
?  Jim Willenbring mentioned in a recent email that a bunch of other packages are having deprecations removed as well (see above).  Did you have to do anything in Albany for these?  I've fixed LCM to work with Tpetra and Xpetra deprecated code OFF, but wasn't sure if I need to do anything for the others.

**Comment by bartgol** [comment]
I did not try to build with BLAH deprecated, for any of the other trilinos packages. The two you mention are the only ones for which I turned OFF deprecated code.

**Comment by ikalash** [comment]
@bartgol : ok good.  Lets hope that is enough....

@lxmota : LCM should be ready to go for when the Tpetra/Xpetra routines get deprecated on Feb. 8.  I'll go ahead and merge my branch with the changes after this date to avoid failures in the interim.

**Comment by lxmota** [comment]
@ikalash Should we use -D Tpetra_ENABLE_DEPRECATED_CODE=OFF in LCM and merge the changes now so that they get included earlier? I would rather do that than wait, specially if I can get some time to test the other deprecation options mentioned above. Oh boy, loads of fun!

**Comment by bartgol** [comment]
@lxmota Albany/LCM only use the new interfaces in Tpetra. So whether you build Trilinos with deprecated ON/OFF should not really matter. Of course,building with deprecated OFF ensures there are no sneaky places where you use old interfaces, but, as Irina points out, there might be _more_ deprecated code from those packages coming out in the next weeks/months, so allowing deprecated code is a way to keep a green cdash for you...

**Comment by lxmota** [comment]
Ok. Well it depends how painful all these deprecations are. I'll try to look into it to see how it affects LCM and whether it's realistic to disable them preemptively or just wait until things break.

**Comment by ikalash** [comment]
If you want to add 
```
-D Tpetra_ENABLE_DEPRECATED_CODE=OFF \
-D Xpetra_ENABLE_DEPRECATED_CODE=OFF \
```
to the nightly LCM builds now, we can merge this branch in, and everything will build / pass.  

I would recommend removing that option in a few weeks though so that we don't get burned by new deprecations added into Tpetra/Xpetra.

**Comment by mperego** [comment]
@lxmota FYI: The date of Feb 8  is when we plan to do a minor release of Trilinos. The actual removal of the deprecated code won't happend right away but several weeks later.

**Comment by mperego** [comment]
@ikalash Yeah, Tpetra deprecated code was the one I was worried about. Anyway, we should check that also the other deprecated code doesn't impact Albany. Next time I build Trilinos I'll try to enable all the options above.

**Comment by ikalash** [comment]
@mperego : that would be great, please let @lxmota and I know what you learn.
