### ISSUE TITLE
Some LCM tests sensitive to OMP settings

### ISSUE THREAD

**Issue by bartgol** [sandialabs/LCM#7]
I was chasing down the issue with a failing test (MechanicsTensileCT), and I finally found the problem: the test passes with OMP_NUM_THREADS=1, but fails otherwise. I am not sure where the problem is, but some of the LCM folks might want to look into this. 

Some extra details. With more than 1 thread, the tests fail due to a failing regression test. Something like

`Response Test 0: 3.066335674548e-05 != 3.068000000000e-05 (rel 1.000000000000e-05 abs 1.000000000000e-08)`

The computed value is deterministic, in the sense that different runs with the same number of threads lead to the same response value. However, different number of threads lead to different response values. This makes me think it is not necessarily a race condition, but I'm not really sure how to explain it otherwise.

Note: this happens on my machine also with master. Compiling with gcc 6.1.0, against Trilinos develop 8e9d4ba . It is not the most recent Trilinos, but I keep 'update trilinos' always as my last resort. Besides, the testsuite is otherwise passing, so I _think_ it is not an issue with Trilinos...

Tagging some LCM people: @ikalash @lxmota

**Comment by ikalash** [comment]
Don't care about OMP anymore.  Closing.
