### ISSUE TITLE
Remove ACEice and ACEpermafrost classes as these are obsolete/not used

### ISSUE THREAD

**Issue by ikalash** [sandialabs/LCM#86]
@lxmota volunteered to do this.

**Comment by ikalash** [comment]
@lxmota : are you OK with me getting rid of these as I make the other mods to the code?

**Comment by lxmota** [comment]
@ikalash Yes, absolutely. Deleting unused code is one of my favorite activities.

**Comment by ikalash** [comment]
This has been done.  Closing.
